run:
  concurrency: 4
  timeout: 10m

skip-dirs:
  - pkg/client

skip-files:
  - pkg/client/.*fake_.*.go

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - lll
    - misspell
    #- staticcheck
    #- structcheck
    #- typecheck
    #- unused
    #- varcheck
    #- prealloc

issues:
  exclude-use-default: false
