/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/ryo-watanabe/k8s-volume-snap/pkg/apis/volumesnapshot/v1alpha1"
	scheme "github.com/ryo-watanabe/k8s-volume-snap/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ObjectstoreConfigsGetter has a method to return a ObjectstoreConfigInterface.
// A group's client should implement this interface.
type ObjectstoreConfigsGetter interface {
	ObjectstoreConfigs(namespace string) ObjectstoreConfigInterface
}

// ObjectstoreConfigInterface has methods to work with ObjectstoreConfig resources.
type ObjectstoreConfigInterface interface {
	Create(ctx context.Context, objectstoreConfig *v1alpha1.ObjectstoreConfig, opts v1.CreateOptions) (*v1alpha1.ObjectstoreConfig, error)
	Update(ctx context.Context, objectstoreConfig *v1alpha1.ObjectstoreConfig, opts v1.UpdateOptions) (*v1alpha1.ObjectstoreConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ObjectstoreConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ObjectstoreConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ObjectstoreConfig, err error)
	ObjectstoreConfigExpansion
}

// objectstoreConfigs implements ObjectstoreConfigInterface
type objectstoreConfigs struct {
	client rest.Interface
	ns     string
}

// newObjectstoreConfigs returns a ObjectstoreConfigs
func newObjectstoreConfigs(c *VolumesnapshotV1alpha1Client, namespace string) *objectstoreConfigs {
	return &objectstoreConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the objectstoreConfig, and returns the corresponding objectstoreConfig object, and an error if there is any.
func (c *objectstoreConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ObjectstoreConfigs that match those selectors.
func (c *objectstoreConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ObjectstoreConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ObjectstoreConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested objectstoreConfigs.
func (c *objectstoreConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a objectstoreConfig and creates it.  Returns the server's representation of the objectstoreConfig, and an error, if there is any.
func (c *objectstoreConfigs) Create(ctx context.Context, objectstoreConfig *v1alpha1.ObjectstoreConfig, opts v1.CreateOptions) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(objectstoreConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a objectstoreConfig and updates it. Returns the server's representation of the objectstoreConfig, and an error, if there is any.
func (c *objectstoreConfigs) Update(ctx context.Context, objectstoreConfig *v1alpha1.ObjectstoreConfig, opts v1.UpdateOptions) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(objectstoreConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(objectstoreConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the objectstoreConfig and deletes it. Returns an error if one occurs.
func (c *objectstoreConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *objectstoreConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched objectstoreConfig.
func (c *objectstoreConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
