/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/ryo-watanabe/k8s-volume-snap/pkg/apis/volumesnapshot/v1alpha1"
	scheme "github.com/ryo-watanabe/k8s-volume-snap/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ObjectstoreConfigsGetter has a method to return a ObjectstoreConfigInterface.
// A group's client should implement this interface.
type ObjectstoreConfigsGetter interface {
	ObjectstoreConfigs(namespace string) ObjectstoreConfigInterface
}

// ObjectstoreConfigInterface has methods to work with ObjectstoreConfig resources.
type ObjectstoreConfigInterface interface {
	Create(*v1alpha1.ObjectstoreConfig) (*v1alpha1.ObjectstoreConfig, error)
	Update(*v1alpha1.ObjectstoreConfig) (*v1alpha1.ObjectstoreConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ObjectstoreConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.ObjectstoreConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ObjectstoreConfig, err error)
	ObjectstoreConfigExpansion
}

// objectstoreConfigs implements ObjectstoreConfigInterface
type objectstoreConfigs struct {
	client rest.Interface
	ns     string
}

// newObjectstoreConfigs returns a ObjectstoreConfigs
func newObjectstoreConfigs(c *VolumesnapshotV1alpha1Client, namespace string) *objectstoreConfigs {
	return &objectstoreConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the objectstoreConfig, and returns the corresponding objectstoreConfig object, and an error if there is any.
func (c *objectstoreConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ObjectstoreConfigs that match those selectors.
func (c *objectstoreConfigs) List(opts v1.ListOptions) (result *v1alpha1.ObjectstoreConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ObjectstoreConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested objectstoreConfigs.
func (c *objectstoreConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a objectstoreConfig and creates it.  Returns the server's representation of the objectstoreConfig, and an error, if there is any.
func (c *objectstoreConfigs) Create(objectstoreConfig *v1alpha1.ObjectstoreConfig) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Body(objectstoreConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a objectstoreConfig and updates it. Returns the server's representation of the objectstoreConfig, and an error, if there is any.
func (c *objectstoreConfigs) Update(objectstoreConfig *v1alpha1.ObjectstoreConfig) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(objectstoreConfig.Name).
		Body(objectstoreConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the objectstoreConfig and deletes it. Returns an error if one occurs.
func (c *objectstoreConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *objectstoreConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched objectstoreConfig.
func (c *objectstoreConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ObjectstoreConfig, err error) {
	result = &v1alpha1.ObjectstoreConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("objectstoreconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
