apiVersion: volumesnapshot.rywt.io/v1alpha1
kind: VolumeRestore
metadata:
  name: cluster02-cluster01-001-001
  namespace: k8s-volume-snap
spec:
  clusterName: cluster02
  volumeSnapshotName: cluster01-001
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akND...
        server: https://cluster01.kubernetes.rywt.nip.io:6443
      name: cluster
    contexts:
    - context:
        cluster: cluster
        user: remote-user
      name: context
    current-context: context
    kind: Config
    preferences: {}
    users:
    - name: remote-user
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVz....
